# 生产环境 III区
server:
  port: 8082
  servlet:
    context-path: /job-schedule
feign:
  name: escluster
  url: http://iii-wabd-004:9200/commpair_alarm
escluster:
  cluster: es_nfdw
  nodes: iii-wabd-003,iii-wabd-004,iii-wabd-005,iii-wabd-006
  port: 9300
  type: default
  commpair_alarm:
    index: commpair_alarm
  security_policy:
    index: communicationalarm
spring:
  data:
    elasticsearch:
      cluster-name: es_nfdw
      cluster-nodes: iii-wabd-003:9300,iii-wabd-004:9300,iii-wabd-005:9300,iii-wabd-006:9300
      repositories:
        enable: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: aling1994
    url: jdbc:mysql://iii-wabd-001:3306/data_extension?characterEncoding=utf8
jedis:
  database: 0
  zk:
    connect:
      host: iii-wabd-003:2181,iii-wabd-004:2181,iii-wabd-005:2181
    session:
      timeout: 5000
    proxy:
      dir: /jodis/codis-test1
  session:
    auth: 123456
  connection:
    timeout: 2000
  sotimeout: 2000
  maxTotal: 1000
  maxIdle: 10
  minIdle: 3
  maxWaitMillis: 10000
  softMinEvictableIdleTimeMillis: 5000
redis:
  key:
    event:
      zz:
        device: deviceInfoGuidbd
        devicetmp: deviceTmpInfoLidbd
        corporation: ui_corporationbd
kafka:
  producer:
    alarms:
      topic: alarms