server:
  port: 8082
feign:
  name: escluster
  url: http://172.16.140.153:9200/hjwindex_test
spring:
  data:
    elasticsearch:
      cluster-name: es_nfdw
      cluster-nodes: zdbd01:9300,zdbd02:9300,zdbd03:9300
      repositories:
        enable: true