# 105开发环境
server:
  port: 8082
  servlet:
    context-path: /job-schedule
feign:
  name: escluster
  url: http://zdbd03:9200
escluster:
  cluster: es_nfdw
  nodes: zdbd01,zdbd02,zdbd03
  port: 9300
  type: default
  commpair_alarm:
    index: commpair_alarm
## 统一放入可以通讯，不再放入爆发式通讯对单独的索引
  security_policy:
    index: security_test
spring:
  data:
    elasticsearch:
      cluster-name: es_nfdw
      cluster-nodes: zdbd01:9300,zdbd02:9300,zdbd03:9300
      repositories:
        enable: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://zdbd02:3306/data_extension?characterEncoding=utf8&useSSL=true
jedis:
  database: 0
  zk:
    connect:
      host: zdbd01:2181,zdbd02:2181,zdbd03:2181
    session:
      timeout: 5000
    proxy:
      dir: /jodis/codis-test1
  session:
    auth: 123456
  connection:
    timeout: 2000
  sotimeout: 2000
  maxTotal: 1000
  maxIdle: 10
  minIdle: 3
  maxWaitMillis: 10000
  softMinEvictableIdleTimeMillis: 5000
redis:
  key:
    event:
      zz:
        device: deviceInfoGuidbd
        devicetmp: deviceTmpInfoLidbd
        corporation: ui_corporationbd
        dcdDeviceIpbd: dcdDeviceIpbd
kafka:
  producer:
    alarms:
      topic: network
    client:
      id: client_id
    batch:
      size: 10240
    linger:
      ms: 100
    buffer:
      memory: 33554432
    request:
      size: 10485760
  bigdata:
    bootstrap:
      servers: zdbd01:9092,zdbd02:9092,zdbd03:9092
