# 生产环境 II区
server:
  port: 8082
  servlet:
    context-path: /job-schedule
feign:
  name: escluster
  url: http://ii-wabd-004:9200/commpair_alarm
escluster:
  cluster: es_nfdw
  nodes: ii-wabd-003,ii-wabd-004,ii-wabd-005,ii-wabd-006
  port: 9300
  type: default
  commpair_alarm:
    index: commpair_alarm
  security_policy:
    index: communicationalarm
spring:
  data:
    elasticsearch:
      cluster-name: es_nfdw
      cluster-nodes: ii-wabd-003:9300,ii-wabd-004:9300,ii-wabd-005:9300,ii-wabd-006:9300
      repositories:
        enable: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ack..mLoca20
    url: jdbc:mysql://ii-wabd-001:3306/data_extension?characterEncoding=utf8